name: 'mathbot'

volumes:
  postgres-data:


networks:
  postgres-network:
    driver: bridge

services:
  postgresql:
    container_name: mathbotdb
    image: 'postgres:15'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    restart: unless-stopped
    volumes:
      # - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - postgres-network

  adminer:
    container_name: adminer-mathbot
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - postgres-network

  mathbot:
    container_name: mathbot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST=postgresql"
      - "TZ=Europe/Moscow"
    #    command: "uvicorn backend.main:app --port ${BACKEND_PORT} --host 0.0.0.0"
    # ports:
    #   - 8000:8000
    networks:
      - postgres-network
